shared: &shared
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password: password

amazon: &amazon
  <<: *shared
  username: user
  password: fair5count
  host: main.cnfssaanjxye.us-east-1.rds.amazonaws.com

development:
  <<: *shared
  database: <%= $globals.app.parameterize.underscore %>_<%= $globals.user %>_development

production:
  <<: *amazon
  database: <%= $globals.app.parameterize.underscore %>

test:
  <<: *shared
  database: <%= $globals.app.parameterize.underscore %>_<%= $globals.user %>_test
